### ISSUE TITLE
Drive Progress Based on Work Package Checklists

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#107]
## Overview
Enable application users to check off expected activities and deliverables within a work package and derive work package progress on % completed, thereby bypassing the relatively convoluted change request process for updating work package progress. 

## Stakeholders
**Product Stakeholder**: @jamescd18 
**Engineering Stakeholder**: @RChandler234 
**Reference Users**: Anushka Wani, Project Management Office

## User Story
As a Project Manager, I want to be able to quickly and accurately understand a work package’s progress as an accurate reflection of the team’s current progress towards completing expected activities and fulfilling deliverables.

## Success Metrics
Success will be measured based on feature usage and adoption, relative to total volume of work packages. As this feature does not currently exist, we will also use a proxy measure as a baseline to compare to.

### Before & After Metrics
Measure volume of created work package expected activities and deliverables. Over the last 3 months, how many work package expected activities and deliverables were added / created each week? This will be used as a reference point to analyze this feature in context.

### Baseline
Measure current frequency of work package progress updates, categorized by start and end value. Over the last 3 months, how many progress changes are there of each category, with categories including `0 to 25`, `0 to 50`, `0 to 100`, `50 to 100`, etc.

### Feature Adoption Metrics
Measure frequency of expected activities and deliverables being check off / marked completed. Over the last week / month, how many expected activities and deliverables were marked completed?

Measure overall progress % immediately after an expected activity or deliverable is marked completed.

## Rollout Plan
- Deployment of features to production: For all completed work packages, indicate their completion date as the completion date of the work package
- Working with initial test users
  - Work with reference users to educate them about how to use the new feature
  - Observe their usage and feedback in initial exploring of features
- Broad club-wide rollout: Host a short training session during an engineering leads meeting

## Out of Scope
- Changes to anything with the project data model

## Background / Context
Currently the progress of a work package is a stored value and something that is included with editing any other part of the work package and thus must have the user input a change request ID to associate the changes with. It thus also logs when the progress changes.

## Acceptance Criteria & Mock-ups

- Work packages with status of `Inactive` or `Complete` cannot have changes made to the completion of expected activities or deliverables

### Work Package View Page
![B06EFF68-81BC-458A-92FB-609DD54F677D](https://user-images.githubusercontent.com/51571627/179566489-c5c44523-8aed-4803-9aa5-2e817a3986bd.jpeg)

- Change expected activities and deliverables from being displayed as bullet points to displayed as checkboxes
- When a bullet is completed, the checkbox is filled in and the text is formatted as strike-through
- When a bullet is completed, on mouse hover, display a tooltip with the full name of the user who completed the bullet and the date when the bullet was completed
- When the checkbox of a bullet that is not completed is clicked, the bullet will be updated as completed by the current user at the current time. The entire expected activities / deliverables page block should display a loading state while this update is pending.
- When the checkbox of a bullet that is completed is clicked, a generic “confirm” dialog should be prompted with “Are you sure you want to mark this completed task as NOT completed?”. If yes, update bullet to remove all completion info. If no, cancel.

### Work Package Edit Form
![FBC60BD8-CD92-44AD-A64C-31AE7F3A918F](https://user-images.githubusercontent.com/51571627/179568099-413a1f82-24db-4506-9211-1521ec8ef30b.jpeg)

- Remove “progress” from the work package edit form, back-end edit endpoint, and database to eliminate manual editing of progress
- The text input and “X” delete button are disabled for any completed expected activities or deliverables

### Tickets

MVP:

- [x] https://github.com/Northeastern-Electric-Racing/FinishLine/issues/186
- [x] https://github.com/Northeastern-Electric-Racing/FinishLine/issues/213
- [x] https://github.com/Northeastern-Electric-Racing/FinishLine/issues/194
- [x] https://github.com/Northeastern-Electric-Racing/FinishLine/issues/189

More Features:

- [x] https://github.com/Northeastern-Electric-Racing/FinishLine/issues/190
- [x] https://github.com/Northeastern-Electric-Racing/FinishLine/issues/192
- [x] https://github.com/Northeastern-Electric-Racing/FinishLine/issues/187
- [x] https://github.com/Northeastern-Electric-Racing/FinishLine/issues/195 - Stage Gate CR Disabled Unless All Checkboxes Checked
- [x] https://github.com/Northeastern-Electric-Racing/FinishLine/issues/325

**Comment by RChandler234** [comment]
Scoping out sub-tickets in epic:

#186 - Convert Expected Activities and Deliverables to Displayed as Checkboxes

**Comment by anthonybernardi** [comment]
all tickets done! nice
