### ISSUE TITLE
Projects - Enable Assigning Users to Projects and Work Packages

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#13]
### Description
Create a method for assigning users to a project/work package.

### Background
It would be beneficial for project leads and project managers to be able to assign engineers to projects/work packages and quickly see who is currently working on what. This can help them organize the engineers and ensure that each project/work package is being worked on by a sufficient number of people.

### Proposed Solution

Create a method for assigning users to a project. Replace the current implementation where project lead is just a single user with marking specific users assigned to a project as project leads. This will enable multiple project leads, and simplify assigning users and project leads for a project. An explicit many-to-many relation in the prisma schema is most likely required.

Ensure that modifications or additions are performed on all the items below
- [ ] data definition interfaces in utils
- [ ] prisma schema
- [ ] prisma seed data
- [ ] prisma seed script
- [ ] project lambda endpoint get prisma query
- [ ] work package lambda endpoint get prisma query
- [ ] project lambda endpoint edit assigned users
- [ ] work package lambda endpoint edit assigned users
- [ ] projects table and tests
- [ ] project details and tests
- [ ] work package details and tests
- [ ] anything else that displays project lead
- [ ] add display of assigned users
- [ ] project stub test data
- [ ] work package stub test data
- [ ] form to edit assigned users
