### ISSUE TITLE
Change Request Redesign

### ISSUE THREAD

**Issue by ryanhowe28** [Northeastern-Electric-Racing/FinishLine#1645]
### Overview

We want to redesign our change request forms to look better and add some new features to the page.

### Stakeholders

Product Stakeholder: Zach Marino, Peyton McKee
Software Stakeholder: Reid Chandler
Reference Users:

### User Story

As a user, I want to see more information on my change request pages, so that I don't need to constantly look for them in the separate tab.

### Success Metrics

Looks much better and users like using added features

### Rollout Plan

All at once

### Out of Scope

Anything other than the CR forms

### Background / Context

The change request forms already exist we are just making it better

### Acceptance Criteria & Mock-ups

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/102765855/78d1ef29-2b84-41a8-b5f6-afec9d0d2821)

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/102765855/01675bfc-9f54-42bd-93d4-8796e6cb3652)
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/102765855/6e894800-75bf-461c-b137-81c9efe376ea)
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/102765855/d5f87bf4-72b5-416e-80f6-b183c45a1b07)

### MVP 
 - [x] #1637 
 - [x] #1638
 - [x] #1639 
 - [x] #1640 
 - [x] #1641 
 - [x] #1642 
 - [x] #1643 
 - [x] #1644
 - [x] #1650

### Improvements/ Bugs 
 - [x] #1728
 - [ ] Add an indicator that a CR is expired on all places they're accessible
 - [ ] Tabs don't git on mobile screens
 - [ ] Cards overflowing on tab dropdown

**Comment by RChandler234** [comment]
done a while ago
