### ISSUE TITLE
User Management - New Admin Page + User Role Selection Section

### ISSUE THREAD

**Issue by leoRysing** [Northeastern-Electric-Racing/FinishLine#259]
## Overview

Create a new admin page, with one main section, where high level users will be able to eventually do a variety of things. For this epic, only add on section, which will be responsible for translating the entire process for changing user roles.

## Stakeholders

Product Stakeholder: @leoRysing 
Software Stakeholder: @joshiarnav 
Reference Users: James

## User Story

As an app admin or a head of the club, I want to be able to have a place to do admin level tasks for the app, so that I can easily edit user permissions in the app instead of needing too outsource this work to James.

## Success Metrics

Success will be measured based on the increase over time of page views. As this feature doesn’t exist, and ideally this specific feature will not need to be used super frequently, the baseline will be set to 0.

### Feature Adoption Metrics

Feature adoption throughout the year can be measured by user traffic relative to current club leadership; admins are heads of the club, and app_admins is currently just Anthony and James. During times when role mishaps can happen, especially when new members join teams that use the dashboard, we can check how many total page visits are given relative to number of users who need their roles adjusted.

## Rollout Plan

- Deploy the new Admin page to production once permissions ensure its only visible to admins and above
- After some brief bug testing, can be announced to admins
Observe difficulties and feedback throughout this process, keeping key attention to any requests that come up for admin specific tasks

## Out of Scope

Out of scope at this time is other concerns for the admin specific page. Eventually we will build out this page with other admin specific sections

### Background / Context

Currently, the entire process anytime user permissions in the app need to be updated is for someone to make a request in the software product requests channel. Then, James has to go and run a script that interacts with the database, to grant the given account a certain role

## Acceptance Criteria & Mock-ups

Create a new page, that is accessible from the sidebar
- [ ] This page should only be accessible for admins (heads) and app admins (Anthony and James or equivalent roles)
- [ ] The title of this page should say Admin Tools

Add one subsection to the page, called "Role Management"
- [ ] Permission roles
- -  [ ] The roles are given below;
- - - [ ] App_admin (James and Anthony)
- - - [ ] Admin (Heads of the club)
- - - [ ] Leadership
- - - [ ] Member
- - - [ ] Guest (Readonly FinishLine; basically a result of our auth requirements)
- - [ ] users can only promote users up to their level (an admin can't promote someone to an app_admin)
- - [ ] users can only demote from below their role (an app_admin can't demote someone to an admin)
- [ ] Have a search bar, where you can enter in a name corresponding to an account that exists in FinishLine
- - [ ] While typing out the name, suggest users it could be
- - [ ] When you find the correct name in the suggestion section, you can click on it, and it will that user as an outlined box with their name
- - [ ] Once you select a user, the dropdown box to the right should become accessible
- - [ ] While no user is selected, display "current role" as the placeholder value, but once a user is selected, the placeholder value should be their current role
- [ ] A dropdown box, for roles
- - [ ] This dropdown will display all roles that are equal to your level and below
- - [ ] Selecting the current role of the user will disable the confirm button
- - [ ] You should be able to select any other role within the constraint that you cannot see roles above your own
- [ ] Once selected, you should be able to click the confirm button
- - [ ] Have some kind of confirmation for success -> loading square, maybe message

## Mocks
The full user flow is shown in [figma](https://www.figma.com/file/qmXuySSwfiD942HwmSSEMe/NERPM-Desktop?node-id=1518%3A1472). Click on present, making sure the shared frame is selected.

Snapshots of this are given below;

![Admin Tools Page](https://user-images.githubusercontent.com/9142777/193958134-18f130f2-f47f-47ae-9caf-b323d39fdd2e.png)
![Admin Tools Page-1](https://user-images.githubusercontent.com/9142777/193958147-3a6b0179-af9e-42a6-a7d6-7eae91e50f63.png)
![Admin Tools Page-2](https://user-images.githubusercontent.com/9142777/193958168-edfe1be0-4e39-481e-8bf9-e6be4690a99e.png)
![Admin Tools Page-3](https://user-images.githubusercontent.com/9142777/193958180-1d70cd97-d453-46fb-a380-cb3d5d3e986a.png)
![Admin Tools Page-4](https://user-images.githubusercontent.com/9142777/193958205-2fd79f9b-5301-407c-8ed0-68887594099f.png)
![Admin Tools Page-7](https://user-images.githubusercontent.com/9142777/193958234-444b4350-403c-47e8-859e-f6c81489f5ed.png)
![Admin Tools Page-5](https://user-images.githubusercontent.com/9142777/193958252-308be2cd-591b-4f2f-85de-315080598eb5.png)
![Admin Tools Page-6](https://user-images.githubusercontent.com/9142777/193958267-cad787b2-720c-4083-a13a-a42ce8143fe4.png)
![Admin Tools Page-8](https://user-images.githubusercontent.com/9142777/193958311-b8a06f53-0fe5-41da-bdfd-e041794be8a3.png)

## Tickets

 - [x] #292 
 - [x] #293 
 - [x] #296

**Comment by jamescd18** [comment]
Failed acceptance testing on local dev as follows, in descending order of importance:

- While the sidebar icon for admin tools properly only appears for APP_ADMIN and ADMIN users, users of any permission level are still capable of visiting the admin tools page by simply navigating to the URL: http://localhost:3000/admin-tools
  - proper front-end security should not only remove UI ability to navigate to restricted pages, but also perform a check on page load to ensure the user has sufficient permissions to see the requested page
  - see [AppPublic](https://github.com/Northeastern-Electric-Racing/FinishLine/blob/develop/src/frontend/src/app/AppPublic.tsx) for existing permission-based page redirect functionality in FinishLine
  - Redirecting the user to the home page is sub-par UX but sufficient for MVP
- Not only can any user access the admin tools page, any user can utilize the role change functionality, indicating that the back-end does not restrict API access to the specified roles
  - specifically, a MEMBER user is capable of elevating a GUEST user to MEMBER role
  - this shouldn't be allowed, the back-end API should deny any requests from users with any role other than APP_ADMIN or ADMIN
- As a user, I find it inconvenient that I cannot see a user's current role prior to selecting them for a role change
  - this could be easily fixed by displaying a user's role in the autocomplete dropdown (NAME - EMAIL - ROLE)
  - this is likely more of an issue with a larger set of users
- As a UI/UX designer, I would have chosen to place the confirm button inline with the other form elements so as to reduce vertical space in preparation for future tools being added to the admin tools page
