### ISSUE TITLE
URL Query Parameters

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#30]
## Prerequisites

- [x] Northeastern-Electric-Racing/PM-Dashboard-v2#404

## Description

Add URL query parameters to various aspects of the application. The two major benefits are: pre-populating forms and preserving filter state.

First, research into the desired design pattern is required. Opening a PR to enhance one small page would be the perfect way to do this.

## User Stories

As an engineer or project manager, I want to share / bookmark / revisit a table with the same filters I had enabled. 

_Embedding filter state into URL query parameters can achieve this._

As an engineer or project manager, I want to manually input as little info as possible to save myself time when filling out a form.

_Pre-populating forms via URL query parameters can achieve this._

## Tickets

- [x] Northeastern-Electric-Racing/FinishLine#31
- [x] Northeastern-Electric-Racing/FinishLine#32
- [x] Northeastern-Electric-Racing/FinishLine#33
- [x] Northeastern-Electric-Racing/PM-Dashboard-v2#511
- [x] Northeastern-Electric-Racing/FinishLine#34
- [x] Northeastern-Electric-Racing/FinishLine#35
- [x] Northeastern-Electric-Racing/FinishLine#91
- [x] Northeastern-Electric-Racing/FinishLine#92

**Comment by anthonybernardi** [comment]
FINALLY LFG
