### ISSUE TITLE
Repository - Resolve Package Vulnerabilities 

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/FinishLine#41]
### Background

Currently, our project still relies on an assortment of deeper dependencies which have vulnerabilities. This shows up when running `npm install` and describes how many vulnerabilities there are. We are currently able to ignore them and move forward with development, but we should make an effort to resolve them, in order of criticality. This should be done incrementally to ensure that we don't break the build.

<img width="390" alt="Screen Shot 2021-12-27 at 7 58 27 PM" src="https://user-images.githubusercontent.com/51571627/147526455-a9bf4a5e-a1ad-470e-a2db-73c8cd63c6d9.png">

### Tickets

 - [ ] Northeastern-Electric-Racing/FinishLine#11
 - [ ] Northeastern-Electric-Racing/FinishLine#42
 - [ ] Northeastern-Electric-Racing/FinishLine#43

**Comment by Ari-S-123** [comment]
![image](https://user-images.githubusercontent.com/80832201/184197959-ae513fb5-b110-41c7-923b-6cd90b77092d.png)
