### ISSUE TITLE
Tasks - Integrate Task Lists Into Projects

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#448]
## Overview:

Add support for Task Lists like the current ones in Google Drive/Sheets. 

## User Story:

As a Project Lead/Manager, I want to be able to create, assign tasks to team members, and complete task lists within Finishline.

As an member, I want to be able to be notified of when I am assigned a task or when a task I am assigned to changes, be able to see it in whatever project I’m working in, and be able to edit the status so that I don’t have to do it in google sheets and so I know what I need to deliver. 

## Success metrics:
Number of changes to status, number of tasks created.

## Out of Scope:
- Integrating into teams section
- Somebody’s todo tasks across all projects
- Tasks attached to a team but not a project

## Background / Context

Currently, users have to create a task list google sheet for their project, fill it out, and link the sheet in Finishline. 

Major benefits of incorporating task lists include ease of creation/editing task, easy selection of assignees, pinging on slack, less links to access and more centralized information on Finishline.

#### Create a new page block in the projects page:
- Title should be “Tasks”
- There will be 3 [tabs](https://mui.com/material-ui/react-tabs/):
     -  “In Progress” (this will be default)
     -  “Backlog”
     -  “Done”
- Each tab will have a [data grid](https://mui.com/x/react-data-grid/) formatted as:
     - “Title” 
     - “Notes”
     - “Deadline” (Date)
     - “Priority” (Low Medium High)
     - “Assignee” 
     - “Date Completed” (Date or its hidden)
     -  “Actions”
- There will be a button on the headerRight of the Page Block “Add New Task”

#### When “Add New Task” Button Pressed
- A new row appears
- Allow user to edit every value of the row
- Title should allow users to enter name of task 
- Assignee should be an [multiple value autocomplete textfield](https://mui.com/material-ui/react-autocomplete/#combo-box)(multiple values) with options of only members of the project’s team, tasks will be able to have multiple assignees
- Actions will Initially have two icons, the one on the left being a save icon and a delete icon that removes the task when pressed.
-  When the save icon is pressed, save the task into the data grid, remove the save icon, and move the delete action into a three line menu.
- The actions for a task are:
  - “Mark as completed”
    - Display when task is under the “In Progress” tab
    - Display with a checkmark icon
    - Disable if user is a guest
  - “Mark as in progress”
    - Display when task is under the “Done” or “Backlog” tabs
    - Display with a PlayArrow icon
    - Disable if user is a guest
  - “Move to backlog”
    - Display when task is under the “In Progress” tab
    - Display with a Pause icon
    - Disable if user is a guest
  - “Delete”
    - Display when task is under any tab
    - Display with a delete icon
    - Disable if user is a guest

#### See Notes Link is pressed:
- Present a modal that encompasses the full text of whatever notes to be added to the task.

#### Editing Status 
- Assignees should be able to edit the status from the project page by double clicking on a cell of the grid
- All select cells should ‘autostop’ when a change is made (view datagrid editing section)

#### Permissions:
- Creating a Task: Only members of the projects team and leadership should be able to create a new task.
- If a member creates a task: Notify the project lead that “task name” was created by “member who created the task”

- Editing a Current task: same permissions as above

- Deleting a task: only project leads and above should be able to do this.

- Slack Notifications for an upcoming deadline: When the upcoming deadline is a day away, notify the assignee that their “Task Name” deadline is tomorrow.

## Mock ups: 

Task List Normally
<img width="500" alt="Screen Shot 2023-01-11 at 12 35 59 PM" src="https://user-images.githubusercontent.com/113635669/211878042-3ca96a94-70bf-43e5-837a-4a1f5440f787.png">

Task List when adding a new task
<img width="500" alt="Screen Shot 2023-01-11 at 12 36 09 PM" src="https://user-images.githubusercontent.com/113635669/211878059-70a7fd61-1bea-425d-a32e-67752eabbf08.png">

Task Lists when menu is selected
<img width="500" alt="Screen Shot 2023-01-11 at 12 36 04 PM" src="https://user-images.githubusercontent.com/113635669/211878052-cfbeedba-b758-473a-b381-76eab0ee438e.png">

Task Lists when notes is selected
<img width="500" alt="Screen Shot 2023-01-11 at 12 36 14 PM" src="https://user-images.githubusercontent.com/113635669/211878066-657f0235-99ce-403c-a7dc-0e8775914c41.png">

### Dev Work

MVP:

- [x] #759
- [x] #788
- [x] #789
- [x] #790
- [x] #791
- [x] #792
- [x] #793
- [x] #760
- [x] #761
- [x] #762
- [x] #763
- [x] #794

Extra Features:

- [ ] #795
- [ ] #878 
- [ ] #921

**Comment by RChandler234** [comment]
MVP:

- [ ]  Tasklists Schema Changes
- [ ] Create Task Endpoint
- [ ] Edit Task Endpoint (title, notes, priority, deadlines)
- [ ] Edit Task assignee endpoint
- [ ] Edit task status (complete, in progress, backlog)
- [ ] Delete Task endpoint
- [ ] Tasklist pageblock skeleton
- [ ] Populate Taskslist pageblock
- [ ] Add Task Functionality
- [ ] Edit Task List Modal
