### ISSUE TITLE
General - MUI Upgrades

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#505]
## Overview

With the introduction of MUI as our front-end framework, a number of different functionality upgrades are possible with new and more powerful components available in MUI. Where it makes sense, we should undertake upgrades to enhance the user experience.

## Tickets

 - [ ] add [quick filter](https://mui.com/x/react-data-grid/pagination/#automatic-page-size) to toolbar
 - [ ] add custom filter operators
 - [ ] add project row actions
 - [ ] add change request row actions
