### ISSUE TITLE
Project - Add Gantt Chart

### ISSUE THREAD

**Issue by leoRysing** [Northeastern-Electric-Racing/FinishLine#51]
## User Stories

As a member of leadership, I want the ability to see the context of work packages in a project I'm working on,to see how different work packages work together, so that I can accurately devote time and make adjustments to different work packages.

A main component that will be used at some point in this epic is the react implementation of Gantt charts. This epic will create the first round implementation of this

## Description

Implement the first iteration of the Gantt chart, specifically for a single project and its work packages.

## Tickets

 - [x] Northeastern-Electric-Racing/PM-Dashboard-v2#596 
 - [ ] Northeastern-Electric-Racing/FinishLine#59 
 - [x] Northeastern-Electric-Racing/PM-Dashboard-v2#624 
 - [x] Northeastern-Electric-Racing/FinishLine#71

**Comment by anthonybernardi** [comment]
redundant now with new gantt stuff
