### ISSUE TITLE
Projects - Risk Log

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/FinishLine#65]
### User Stories

As a club member, I want to be able to note down potential risks associated with a project, so that ideas/risks/issues that come up during a project's lifecycle are documented and visible for everyone to see. 

### Background

This epic is associated with building a new risk log feature that is requested by project managers. The risk log will be used by members to keep track of issues that come up as they work on a project. For each project, a "Risk Log" section will be added to the project details page where users can add, resolve, or use a risk to begin filling out a change request form. The idea of the risk log is similar to the "Reminders" app from Apple.

### Tickets

 - [x] Northeastern-Electric-Racing/PM-Dashboard-v2#696 Visuals with create new CR btn
 - [x] Northeastern-Electric-Racing/PM-Dashboard-v2#698 Edit Project schema to include risk log. Should create new risk log model? Or just use String[]? Cause at the most basic level, the model will only have two fields (String text and Boolean resolved)
 - [x] Northeastern-Electric-Racing/FinishLine#66 Create risk endpoint
 - [x] Northeastern-Electric-Racing/FinishLine#69
 - [x] Northeastern-Electric-Racing/FinishLine#67 Delete risk endpoint - backend validation to make sure it is resolved
 - [x] Northeastern-Electric-Racing/FinishLine#70
 - [x] Northeastern-Electric-Racing/FinishLine#68
 
#### Tickets below should be worked on only after the above tickets are finished
  - [ ] Inline editing of risk's text - frontend

**Comment by anthonybernardi** [comment]
done, woohoo!!!
