### ISSUE TITLE
Projects - Wire Up Risk Log

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/FinishLine#68]
### Description

The front-end visuals and backend endpoints for risk logs have been created in Northeastern-Electric-Racing/PM-Dashboard-v2#696, Northeastern-Electric-Racing/FinishLine#66, Northeastern-Electric-Racing/FinishLine#69, and Northeastern-Electric-Racing/PM-Dashboard-v2#701. This ticket is to complete the feature of creating, resolving, and deleting risks by wiring up the front-end list to the endpoint and have it properly send and get data to and from the associated endpoint.

### Background

Wiring up the risk log to the created endpoints is the last step in completing the feature for risk logs. See Northeastern-Electric-Racing/PM-Dashboard-v2#448 for an example wiring ticket pull request.

### Prerequisites 

These tickets need to be completed before working on the current ticket:
- [x] Northeastern-Electric-Racing/PM-Dashboard-v2#696
- [x] Northeastern-Electric-Racing/FinishLine#66
- [x] Northeastern-Electric-Racing/FinishLine#69
- [x] Northeastern-Electric-Racing/FinishLine#67

### Proposed Solution

Gather together data from the front-end textbox into state management storage in the container component. Then facilitate packaging and sending the data to the back-end and getting and displaying the data from the back-end by:

- [x] writing the api functions
- [x] writing the custom hooks
- [x] implementing the custom hooks

Ensure all aspects of the risk create, resolve, and delete features are present and functioning. Verify by tracing data from user input through the full stack to database ingestion. Implement / fix / write tests for any of the following elements in the trace through the tech stack that are not behaving as expected.

- [x] Resolve button
- [x] Add new risk button
- [x] Delete button
- [x] Textbox input field
- [x] Create custom mutation hook for sending/getting data to/from the backend 
- [x] Create API function for sending/getting data to/from backend
- [x] Integrate custom mutation hook and API into front-end
- [x] Api route string
- [x] Api route function
- [x] Payload validation
- [x] Database insertion
- [x] Api response
