### ISSUE TITLE
Proposed Solutions

### ISSUE THREAD

**Issue by tigerhippo** [Northeastern-Electric-Racing/FinishLine#80]
## Description

Add support for addition of arbitrary number of proposed solutions when making a change request. 

## User Stories

As a project manager or project lead, I want to be able to add an arbitrary number of solutions when I make a change request, so that the head of my project can more accurately see the ways I want to resolve a change request.  

## Background

After this epic is completed, the user will be able to add anywhere from 0 to N proposed solutions when they make a change request. If one solution doesn't work, I can easily suggest a new direction within the same change request. Heads can select a proposed solution to move forward with when accepting the change request. At least one proposed solution needs to be approved before the change request can be approved. 

## Business Logic

Each proposed solution has a plus sign icon that adds a block with four elements.

The four elements are:
- [x] A description (String)
- [x] A budget (Number)
- [x] A timeline (Number—number of weeks)
- [x] A scope (String)

### Tickets

 - [x] Northeastern-Electric-Racing/FinishLine#83 
 - [x] Northeastern-Electric-Racing/FinishLine#84 
 - [x] Northeastern-Electric-Racing/FinishLine#85 
 - [x] Northeastern-Electric-Racing/FinishLine#86 
 - [x] Northeastern-Electric-Racing/FinishLine#87 
 - [x] Northeastern-Electric-Racing/FinishLine#88 
 - [x] Northeastern-Electric-Racing/FinishLine#89 
 - [x] Northeastern-Electric-Racing/FinishLine#212

Extension Tickets
 - [x] Northeastern-Electric-Racing/FinishLine#82
