### ISSUE TITLE
Gantt Chart

### ISSUE THREAD

**Issue by z-roth** [Northeastern-Electric-Racing/FinishLine#90]
## Overview
Create a new Page, the projects Gantt chart, thereby supporting the carryover of the google sheets solution.

## Stakeholders
**Product Stakeholder**: @jamescd18, @leoRysing 
**Engineering Stakeholder**: @RChandler234 
**Reference Users**: Jessica Shang, Anushka Wani

## User Stories

As a project manager/lead, I want to be able to have easy access to information regarding a project's timeline, position in relation to other projects and its completion status. By using a Gantt chart, I can easily gleam said information from a diagram.

## Success Metrics

Success will be measured based on the frequency of interaction with this page.

We can record the baseline for this using the Google Activity Dashboard. Namely, we can check the **Viewers** and **Viewer Trends** pages. From there, a simple count is sufficient.

In the app, we can record these using user sessions every time someone accesses the new Gantt page.
- This feature will be successful if we get similar number of unique users over <X_duration>.

**Google Spreadsheet Number of Unique Users:** 6 (based on <# of unique users> from August 2nd to August 17th)
**Google Spreadsheet Daily Avg Users:** 1.62 [round up to 2] (based on <# of users on a given day> averaged from July 27th to August 17th)

Some fun bonus metrics for the dashboard could be adding in timestamps to track the total number of activities to this page.

Activity is as follows;
1.  People navigating to the Gantt chart page
2. People filtering options on the Gantt chart page
3. People clicking from the Gantt chart page

## Background

The current Gantt chart is functional but leaves much to be desired, especially outside of the scope of an individual project. This feature is a high priority as it is a highly-requested feature that greatly. Currently, it only exists as a Spreadsheet solution.

The existing gantt is found at;
https://docs.google.com/spreadsheets/d/1KMaX7BX4c7TXwEU0zSwl87XUk_U6zp7as5WFV6ToyFM/edit#gid=0

## Prerequisites

Prerequisite Tickets;
 - [x] #135 
 - [x] #136 
 
## Acceptance Criteria and Mocks

When created, there should be a new page in the FinishLine menu for the Gantt Chart 

This page should be a large gantt chart. Translate the design of the work package gantt with our existing projects..

Translating the above, the gantt should have the following;
- [x] Each entry should be for a project
- [x] Each project should have its name and its WBS number
  - [x] These top two should work as the label for each project, on the left side of the gantt
- [x] The remainder of the Gantt will be devoted to the timeline calendar
  - [ ] Have a weekly breakdown, with each week starting on the monday
  - [x] The corresponding bar of the project should start at its start date, and stretch proportional to its duration
  - [x] It should use the gantt color feature as a short hand for its percent completion
- [x] When you hover over a project, more info should show up;
  - [x]  You should have its WBS Number and Name on the top of the hover
  - [x] Directly to the right of this, put the start date
  - [x] Add its duration below that
  - [x] Below that, show its duration
  - [x] Below that, show its end date

A mock for this is a follows;
Ignore the filter in the mocks, filters for Gantt is not in scope for this epic.
<img width="803" alt="Screen Shot 2022-08-27 at 6 19 29 PM" src="https://user-images.githubusercontent.com/9142777/187049923-87cd14a2-1edc-468a-abeb-03603eeae3c4.png">

Hover should provide more info about these projects;
<img width="798" alt="Screen Shot 2022-08-27 at 6 19 37 PM" src="https://user-images.githubusercontent.com/9142777/187049937-f9c878c5-627d-4052-84a3-f3569d04fe6e.png">

If possible, some way to group projects is advisable, may need further investigation.

### Tickets

- [x] #25 
- [x] #286 
- [x] #284 
- [x] #530
