### ISSUE TITLE
General - MVP Base Functionality Adjustments

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#95]
## Description

Various adjustments to the functionality of the application to clean it up and prepare it for the baseline MVP launch.

## Background

We built the MVP according to previous Epics like Northeastern-Electric-Racing/PM-Dashboard-v2#374, but in doing so, we may have missed little details here and there that make a difference in the application's functionality.

## Tickets

- [x] Northeastern-Electric-Racing/FinishLine#44
- [x] Northeastern-Electric-Racing/PM-Dashboard-v2#540
- [x] Northeastern-Electric-Racing/PM-Dashboard-v2#555
- [x] Northeastern-Electric-Racing/PM-Dashboard-v2#554
