### ISSUE TITLE
General - MVP Launch Clean-up

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#99]
## Overview

Various different cleaning is necessary for launching the application to users for the MVP.

First we will find things, then we will triage, then we will fix them in priority order.

## Things we find and do for MVP
- [x] Remove unused fields for project `Expected Progress` and `Timeline Status` (#114 )
- [x] fix change request apply and clear filters buttons to swap places and not be reversed from projects filter
- [x] Northeastern-Electric-Racing/PM-Dashboard-v2#610
- [x] Northeastern-Electric-Racing/PM-Dashboard-v2#613

## Things to make tickets for and maybe do later
- [ ] Factor out users select dropdown into its own component and sort users alphabetically
- [x] Northeastern-Electric-Racing/FinishLine#56
- [ ] Fix dates in general
  - [ ] How does [`formatDate`](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/4a6b9d3929320c4a64a962583b66c9f2e622e1d2/src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-details/work-package-details.tsx#L18) compare to [`transformDate`](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/4a6b9d3929320c4a64a962583b66c9f2e622e1d2/src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-edit-details/work-package-edit-details.tsx#L167) and why is `formatDate` still in the code but not used?
- [ ] Fix error handling for edit forms to surface better error messages
- [ ] Fix focusing of description bullet boxes when changing to edit mode so it doesn't pull you down to the box as soon as you enter edit mode
- [ ] investigate sort order of work packages within a project page

**Comment by anthonybernardi** [comment]
all the tickets are done so that's good enough for me
